#!/bin/bash

set -e

if [ -z $1 ]; then
  echo "Please give a repository with the packaging in."
  exit 1
fi

repo=$1
VERSION=$(make version)
srcdir=$PWD
pkgbuilddir=$srcdir/_package
upstream_name=ContextKit
deb_source_name=contextkit

deb_orig_name=$deb_source_name'_'$VERSION.orig.tar.gz

cd $srcdir && make dist distdir=$deb_source_name-$VERSION

rm -rf $pkgbuilddir

mkdir $pkgbuilddir
mv $srcdir/$deb_source_name-$VERSION.tar.gz $pkgbuilddir/$deb_orig_name
tar -C $pkgbuilddir -xzf $pkgbuilddir/$deb_orig_name

git clone $repo $pkgbuilddir/$upstream_name-packaging

cp -r $pkgbuilddir/$upstream_name-packaging/debian $pkgbuilddir/$deb_source_name-$VERSION/

if cd $pkgbuilddir/$deb_source_name-$VERSION && dch -d -D harmattan; then
  read -p "Push this version to packaging? [y] "
  if [ "x$REPLY" = "x" -o "x$REPLY" = "xy" ]; then
    cp $pkgbuilddir/$deb_source_name-$VERSION/debian/changelog $pkgbuilddir/$upstream_name-packaging/debian/changelog
    cd $pkgbuilddir/$upstream_name-packaging
    git commit debian/changelog -m "New version"
    git push
  fi
  cd $pkgbuilddir/$deb_source_name-$VERSION/ && debuild -S -sa -d -us -uc
fi

