######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 15 11:49:08 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myobject.h mythread.h queuedinvoker.h
SOURCES += main.cpp queuedinvoker.cpp
