TEST_PROGS += \
	tests/intset					\
	tests/stringset					\
	$(NULL)

noinst_PROGRAMS = $(TEST_PROGS)

BUILT_SOURCES += \
	tests/intset.vala.stamp				\
	tests/stringset.vala.stamp			\
	$(NULL)

tests_intset_VALASOURCES = \
	src/intset.vapi 				\
	tests/intset.vala				\
	$(NULL)

tests_intset_GENERATED_SOURCES = \
	$(tests_intset_VALASOURCES:.vala=.c)		\
	$(tests_intset_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_intset_SOURCES = \
	$(tests_intset_GENERATED_SOURCES)		\
	src/intset.c					\
	src/intset.h					\
	$(NULL)

tests/intset.vala.stamp: $(tests_intset_VALASOURCES)
	$(VALAC) -C --basedir $(top_srcdir) $^
	touch $@

tests_intset_CFLAGS = -I$(top_srcdir)/src $(CONTEXTD_CFLAGS)
tests_intset_LDADD = $(CONTEXTD_LIBS)

tests_stringset_VALASOURCES = \
	src/intset.vapi				\
	src/StringSet.vala				\
	tests/stringset.vala				\
	$(NULL)

tests_stringset_GENERATED_SOURCES = \
	$(tests_stringset_VALASOURCES:.vala=.c)		\
	$(tests_stringset_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_stringset_SOURCES = \
	$(tests_stringset_GENERATED_SOURCES)		\
	src/intset.c					\
	src/intset.h					\
	$(NULL)

tests/stringset.vala.stamp: $(tests_stringset_VALASOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 $^
	touch $@

tests_stringset_CFLAGS = -I$(top_srcdir)/src $(CONTEXTD_CFLAGS)
tests_stringset_LDADD = $(CONTEXTD_LIBS)

EXTRA_DIST += \
	$(tests_intset_VALASOURCES)			\
	tests/intset.vala.stamp				\
	$(tests_stringset_VALASOURCES)			\
	tests/stringset.vala.stamp			\
	$(NULL)

DISTCLEANFILES += \
	$(tests_intset_VALASOURCES)			\
	tests/intset.vala.stamp				\
	$(tests_stringset_VALASOURCES)			\
	tests/stringset.vala.stamp			\
	$(NULL)


