######################################################################
# Automatically generated by qmake (2.01a) Tue May 12 17:17:46 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
