TEST_PROGS += \
	tests/unit_tests/intset					\
	tests/unit_tests/stringset					\
	tests/unit_tests/value_compare\
	$(NULL)

noinst_PROGRAMS = $(TEST_PROGS)

BUILT_SOURCES += \
	tests/unit_tests/intset.vala.stamp				\
	tests/unit_tests/stringset.vala.stamp			\
	tests/unit_tests/value_compare.vala.stamp			\
	$(NULL)

tests_unit_tests_intset_VAPISOURCES = \
	libcontextprovider/intset.vapi               \
	$(NULL)

tests_unit_tests_intset_VALASOURCES = \
	tests/unit_tests/intset.vala				\
	$(NULL)

tests_unit_tests_intset_GENERATEDSOURCES = \
	$(tests_unit_tests_intset_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_intset_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_unit_tests_intset_SOURCES = \
	$(tests_unit_tests_intset_GENERATEDSOURCES)		\
	libcontextprovider/intset.c					\
	libcontextprovider/intset.h					\
	$(NULL)

tests/unit_tests/intset.vala.stamp: $(tests_unit_tests_intset_VALASOURCES) $(tests_unit_tests_intset_VAPISOURCES)
	$(VALAC) -C --basedir $(top_srcdir) $^
	touch $@

tests_unit_tests_intset_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_intset_LDADD = $(CONTEXTD_LIBS)

tests_unit_tests_stringset_VAPISOURCES = \
	libcontextprovider/intset.vapi				\
	$(NULL)

tests_unit_tests_stringset_VALASOURCES = \
	libcontextprovider/string_set.vala				\
	tests/unit_tests/stringset.vala				\
	$(NULL)

tests_unit_tests_stringset_GENERATEDSOURCES = \
	$(tests_unit_tests_stringset_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_stringset_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_unit_tests_stringset_SOURCES = \
	$(tests_unit_tests_stringset_GENERATEDSOURCES)		\
	libcontextprovider/intset.c					\
	libcontextprovider/intset.h					\
	$(NULL)

tests/unit_tests/stringset.vala.stamp: $(tests_unit_tests_stringset_VALASOURCES) $(tests_unit_tests_stringset_VAPISOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 $^
	touch $@

tests_unit_tests_stringset_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_stringset_LDADD = $(CONTEXTD_LIBS)


tests_unit_tests_value_compare_VALASOURCES = \
	libcontextprovider/value_compare.vala				\
	tests/unit_tests/test_value_compare.vala			\
	$(NULL)

tests_unit_tests_value_compare_GENERATEDSOURCES = \
	$(tests_unit_tests_value_compare_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_value_compare_VALASOURCES:.vala=.h)		\
	$(NULL)

tests/unit_tests/value_compare.vala.stamp: $(tests_unit_tests_value_compare_VALASOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 $^
	touch $@

tests_unit_tests_value_compare_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_value_compare_LDADD = $(CONTEXTD_LIBS)


EXTRA_DIST += \
	$(tests_unit_tests_intset_VALASOURCES)				\
	$(tests_unit_tests_intset_VAPISOURCES)				\
	$(tests_unit_tests_intset_GENERATEDSOURCES)			\
	tests/unit_tests/intset.vala.stamp				\
	$(tests_unit_tests_stringset_VALASOURCES)			\
	$(tests_unit_tests_stringset_VAPISOURCES)                       \
	$(tests_unit_tests_stringset_GENERATEDSOURCES)			\
	tests/unit_tests/stringset.vala.stamp			\
	$(tests_unit_tests_value_compare_VALASOURCES)			\
	$(tests_unit_tests_value_compare_GENERATEDSOURCES)		\
	tests/unit_tests/value_compare.vala.stamp			\
	$(NULL)

DISTCLEANFILES += \
	$(NULL)

MAINTAINERCLEANFILES += \
	$(tests_unit_tests_intset_GENERATEDSOURCES)			\
	tests/unit_tests/intset.vala.stamp				\
	$(tests_unit_tests_stringset_GENERATEDSOURCES)			\
	tests/unit_tests/stringset.vala.stamp				\
	$(tests_unit_tests_value_compare_GENERATEDSOURCES)		\
	tests/unit_tests/value_compare.vala.stamp			\
	$(NULL)
