TEST_PROGS += \
	tests/unit_tests/intset					\
	tests/unit_tests/stringset				\
	tests/unit_tests/value_compare				\
	tests/unit_tests/group					\
	tests/unit_tests/grouplist				\
	tests/unit_tests/key_usage_counter				\
	tests/unit_tests/subscriber				\
	tests/unit_tests/manager				\
	$(NULL)

noinst_PROGRAMS = $(TEST_PROGS)

BUILT_SOURCES += \
	tests/unit_tests/intset.vala.stamp			\
	tests/unit_tests/stringset.vala.stamp			\
	tests/unit_tests/value_compare.vala.stamp		\
	tests/unit_tests/group.vala.stamp		\
	tests/unit_tests/grouplist.vala.stamp		\
	tests/unit_tests/key_usage_counter.vala.stamp		\
	tests/unit_tests/subscriber.vala.stamp		\
	tests/unit_tests/manager.vala.stamp		\
	$(NULL)

tests_unit_tests_intset_VAPISOURCES = \
	libcontextprovider/intset.vapi               \
	$(NULL)

tests_unit_tests_intset_VALASOURCES = \
	tests/unit_tests/intset.vala				\
	$(NULL)

tests_unit_tests_intset_GENERATEDSOURCES = \
	$(tests_unit_tests_intset_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_intset_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_unit_tests_intset_SOURCES = \
	$(tests_unit_tests_intset_GENERATEDSOURCES)		\
	libcontextprovider/intset.c					\
	libcontextprovider/intset.h					\
	$(NULL)

tests/unit_tests/intset.vala.stamp: $(tests_unit_tests_intset_VALASOURCES) $(tests_unit_tests_intset_VAPISOURCES)
	$(VALAC) -C --basedir $(top_srcdir) $^
	touch $@

tests_unit_tests_intset_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_intset_LDADD = $(CONTEXTD_LIBS)

tests_unit_tests_stringset_VAPISOURCES = \
	libcontextprovider/intset.vapi				\
	$(NULL)

tests_unit_tests_stringset_VALASOURCES = \
	libcontextprovider/string_set.vala				\
	tests/unit_tests/stringset.vala				\
	$(NULL)

tests_unit_tests_stringset_GENERATEDSOURCES = \
	$(tests_unit_tests_stringset_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_stringset_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_unit_tests_stringset_SOURCES = \
	$(tests_unit_tests_stringset_GENERATEDSOURCES)		\
	libcontextprovider/intset.c					\
	libcontextprovider/intset.h					\
	$(NULL)

tests/unit_tests/stringset.vala.stamp: $(tests_unit_tests_stringset_VALASOURCES) $(tests_unit_tests_stringset_VAPISOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 $^
	touch $@

tests_unit_tests_stringset_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_stringset_LDADD = $(CONTEXTD_LIBS)


tests_unit_tests_value_compare_VALASOURCES = \
	libcontextprovider/value_compare.vala				\
	tests/unit_tests/test_value_compare.vala			\
	$(NULL)

tests_unit_tests_value_compare_SOURCES = \
	$(tests_unit_tests_value_compare_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_value_compare_VALASOURCES:.vala=.h)		\
	$(NULL)

tests/unit_tests/value_compare.vala.stamp: $(tests_unit_tests_value_compare_VALASOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 $^
	touch $@

tests_unit_tests_value_compare_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_value_compare_LDADD = $(CONTEXTD_LIBS)

tests_unit_tests_group_VALASOURCES = \
	tests/unit_tests/test_group.vala			\
	$(NULL)

tests_unit_tests_group_SOURCES = \
	$(tests_unit_tests_group_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_group_VALASOURCES:.vala=.h)		\
	$(NULL)

tests/unit_tests/group.vala.stamp: contextprovider.vapi $(tests_unit_tests_group_VALASOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 --pkg dbus-glib-1 $^
	touch $@


tests_unit_tests_group_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_group_LDADD = $(CONTEXTD_LIBS) $(top_builddir)/libcontextprovider.la

tests_unit_tests_grouplist_VALASOURCES = \
	tests/unit_tests/test_grouplist.vala			\
	$(NULL)

tests_unit_tests_grouplist_SOURCES = \
	$(tests_unit_tests_grouplist_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_grouplist_VALASOURCES:.vala=.h)		\
	$(NULL)

tests/unit_tests/grouplist.vala.stamp: contextprovider.vapi $(tests_unit_tests_grouplist_VALASOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 --pkg dbus-glib-1 $^
	touch $@


tests_unit_tests_grouplist_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_grouplist_LDADD = $(CONTEXTD_LIBS) $(top_builddir)/libcontextprovider.la

tests_unit_tests_key_usage_counter_VALASOURCES = \
	tests/unit_tests/test_key_usage_counter.vala			\
	$(NULL)

tests_unit_tests_key_usage_counter_SOURCES = \
	$(tests_unit_tests_key_usage_counter_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_key_usage_counter_VALASOURCES:.vala=.h)		\
	$(NULL)

tests/unit_tests/key_usage_counter.vala.stamp: contextprovider.vapi $(tests_unit_tests_key_usage_counter_VALASOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 --pkg dbus-glib-1 $^
	touch $@

tests_unit_tests_key_usage_counter_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_key_usage_counter_LDADD = $(CONTEXTD_LIBS) $(top_builddir)/libcontextprovider.la

tests_unit_tests_subscriber_VAPISOURCES = \
	libcontextprovider/intset.vapi				\
	$(NULL)

tests_unit_tests_subscriber_VALASOURCES = \
	libcontextprovider/value_compare.vala				\
	libcontextprovider/subscriber.vala				\
	libcontextprovider/manager.vala				\
	libcontextprovider/key_usage_counter.vala				\
	libcontextprovider/string_set.vala				\
	libcontextprovider/group.vala				\
	libcontextprovider/grouplist.vala				\
	libcontextprovider/dbus_interface.vala				\
	libcontextprovider/context_provider.vala				\
	tests/unit_tests/test_subscriber.vala			\
	$(NULL)

tests_unit_tests_subscriber_GENERATEDSOURCES = \
	$(tests_unit_tests_subscriber_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_subscriber_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_unit_tests_subscriber_SOURCES = \
	$(tests_unit_tests_subscriber_GENERATEDSOURCES)		\
	libcontextprovider/intset.c					\
	libcontextprovider/intset.h					\
	$(NULL)

tests/unit_tests/subscriber.vala.stamp: $(tests_unit_tests_subscriber_VALASOURCES) $(tests_unit_tests_subscriber_VAPISOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 --pkg dbus-glib-1 $^
	touch $@

tests_unit_tests_subscriber_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_subscriber_LDADD = $(CONTEXTD_LIBS) $(top_builddir)/libcontextprovider.la

tests_unit_tests_manager_VAPISOURCES = \
	libcontextprovider/intset.vapi				\
	$(NULL)

tests_unit_tests_manager_VALASOURCES = \
	libcontextprovider/value_compare.vala				\
	libcontextprovider/manager.vala				\
	libcontextprovider/subscriber.vala				\
	libcontextprovider/context_provider.vala				\
	libcontextprovider/key_usage_counter.vala				\
	libcontextprovider/string_set.vala				\
	libcontextprovider/group.vala				\
	libcontextprovider/grouplist.vala				\
	libcontextprovider/dbus_interface.vala				\
	tests/unit_tests/test_manager.vala			\
	$(NULL)

tests_unit_tests_manager_GENERATEDSOURCES = \
	$(tests_unit_tests_manager_VALASOURCES:.vala=.c)		\
	$(tests_unit_tests_manager_VALASOURCES:.vala=.h)		\
	$(NULL)

tests_unit_tests_manager_SOURCES = \
	$(tests_unit_tests_manager_GENERATEDSOURCES)		\
	libcontextprovider/intset.c					\
	libcontextprovider/intset.h					\
	$(NULL)

tests/unit_tests/manager.vala.stamp: $(tests_unit_tests_manager_VALASOURCES) $(tests_unit_tests_manager_VAPISOURCES)
	$(VALAC) -C --basedir $(top_srcdir) --vapidir=$(top_srcdir)/vapi --pkg gee-1.0 --pkg dbus-glib-1 $^
	touch $@

tests_unit_tests_manager_CFLAGS = -I$(top_srcdir)/libcontextprovider $(CONTEXTD_CFLAGS)
tests_unit_tests_manager_LDADD = $(CONTEXTD_LIBS) $(top_builddir)/libcontextprovider.la

EXTRA_DIST += \
	$(tests_unit_tests_intset_VALASOURCES)				\
	$(tests_unit_tests_intset_VAPISOURCES)				\
	$(tests_unit_tests_intset_GENERATEDSOURCES)			\
	tests/unit_tests/intset.vala.stamp				\
	$(tests_unit_tests_stringset_VALASOURCES)			\
	$(tests_unit_tests_stringset_VAPISOURCES)                       \
	$(tests_unit_tests_stringset_GENERATEDSOURCES)			\
	tests/unit_tests/stringset.vala.stamp			\
	$(tests_unit_tests_value_compare_VALASOURCES)			\
	$(tests_unit_tests_value_compare_SOURCES)		\
	tests/unit_tests/value_compare.vala.stamp			\
	$(tests_unit_tests_group_VALASOURCES)			\
	$(tests_unit_tests_group_SOURCES)		\
	tests/unit_tests/group.vala.stamp			\
	$(tests_unit_tests_key_usage_counter_VALASOURCES)			\
	$(tests_unit_tests_key_usage_counter_SOURCES)		\
	tests/unit_tests/key_usage_counter.vala.stamp			\
	$(tests_unit_tests_subscriber_VALASOURCES)			\
	$(tests_unit_tests_subscriber_VAPISOURCES)			\
	$(tests_unit_tests_subscriber_GENERATEDSOURCES)		\
	tests/unit_tests/subscriber.vala.stamp			\
	$(tests_unit_tests_manager_VALASOURCES)			\
	$(tests_unit_tests_manager_VAPISOURCES)			\
	$(tests_unit_tests_manager_GENERATEDSOURCES)		\
	tests/unit_tests/manager.vala.stamp			\
	$(NULL)

DISTCLEANFILES += \
	$(NULL)

MAINTAINERCLEANFILES += \
	$(tests_unit_tests_intset_GENERATEDSOURCES)			\
	tests/unit_tests/intset.vala.stamp				\
	$(tests_unit_tests_stringset_GENERATEDSOURCES)			\
	tests/unit_tests/stringset.vala.stamp				\
	$(tests_unit_tests_value_compare_SOURCES)			\
	tests/unit_tests/value_compare.vala.stamp			\
	$(tests_unit_tests_group_SOURCES)			\
	tests/unit_tests/group.vala.stamp			\
	$(tests_unit_tests_grouplist_SOURCES)			\
	tests/unit_tests/grouplist.vala.stamp			\
	$(tests_unit_tests_key_usage_counter_SOURCES)			\
	tests/unit_tests/key_usage_counter.vala.stamp			\
	$(tests_unit_tests_subscriber_GENERATEDSOURCES)			\
	tests/unit_tests/subscriber.vala.stamp			\
	$(tests_unit_tests_manager_GENERATEDSOURCES)			\
	tests/unit_tests/manager.vala.stamp			\
	$(NULL)
