######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 24 14:21:24 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src
LIBS += ../../src/.libs/libcontextsubscriber.a -lcdb
CONFIG += qxml qdbus


# Input
HEADERS += thread.h
SOURCES += main.cpp
