######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 11 10:45:19 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src
LIBS += ../../src/.libs/libcontextsubscriber.a -lcdb
CONFIG += qxml qdbus

# Input
HEADERS += thread.h
SOURCES += main.cpp
