######################################################################
# Automatically generated by qmake (2.01a) Mon May 11 10:37:00 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += dbus

# Input
SOURCES += main.cpp
HEADERS += test.h watcher.h
