.TH context-print-info 1 July-03-2009
.SH NAME
context-print-info
- a simple client to print out the registry information of given properties
.SH SYNOPSIS
.B context-print-info\fR [\fIPROPERTY\fR]...
.SH DESCRIPTION
context-print-info prints out the following information for the
properties given as parameter: key, existence in registy, provider
D-Bus type and name, and documentation.
.SH ENVIRONMENT VARIABLES
.TP 8
CONTEXT_PROVIDERS
may define a directory containing the provider descriptor cdb or XML
files. If it is not set, a compiled-in registry prefix path will be used (usually
/usr/share/contextkit/providers).
.SH ARGUMENTS
context-print-info takes a list of properties as arguments.
Properties are dot separated names, like Context.Location.Latitude.
.SH SEE ALSO
context-listen(1)
