.TH update-tool 1 May-18-2009
.SH NAME
update-tool
- updates the cached context-providers.cdb context properties registry database.
.SH SYNOPSIS
.B update-tool [directory]
.SH DESCRIPTION
update-tool reads the context properties registry (in xml format) and produces an updated cached database - context-providers.cdb. The database is used by libcontextsubscrbier for quick introspection of the registry.
.SH OPTIONS
.TP 13
directory
the location containing the xml registry. The database will be written there. 
If no directory is specified, update-tool will use the CONTEXT_PROVIDERS environment variable. 
If that is not preset as well, a compiled-in registry prefix path will be used.
