######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 15 14:13:34 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src
LIBS += ../../src/.libs/libcontextsubscriber.a -lcdb
CONFIG += qxml qdbus

# Input
HEADERS += thread.h
SOURCES += main.cpp
