#! /bin/sh

# add-release-tag -- turn a skeleton source tree that is appropriate for
#                 	trunk or a branch into a full source tree that is
#                 	appropriate for a tag.
# 
# We do this by building a dist tarball as a reference and add all
# files that end up in that tarball to subversion.
# 

tarname=$1
version=$2

git checkout -b tmp
./autogen.sh --enable-gtk-doc
make
make dist distdir=$tarname

git add -f `tar tzf $tarname.tar.gz | sed s,^$tarname/,,`
git commit -m "Complete for distribution."
git tag -a $version -m "Released $version"
git push --tags
git checkout master
git branch -D tmp
