/* intset.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "ContextProvider", lower_case_cprefix = "context_provider_")]
namespace ContextProvider {
	[Compact]
	[CCode (copy_function = "context_provider_intset_copy", free_function = "context_provider_intset_destroy", cheader_filename = "intset.h")]
	internal extern class IntSet {
		[CCode (cname = "context_provider_intset_new", has_construct_function = false)]
		public extern IntSet ();
		[CCode (cname = "context_provider_intset_sized_new")]
		public extern IntSet.sized (uint size);
		[CCode (cname = "context_provider_intset_intersection")]
		public extern IntSet.intersection (IntSet left, IntSet right);
		[CCode (cname = "context_provider_intset_symmetric_difference")]
		public extern IntSet.symmetric_difference (IntSet left, IntSet right);
		[CCode (cname = "context_provider_intset_difference")]
		public extern IntSet.difference (IntSet left, IntSet right);
		[CCode (cname = "context_provider_intset_union")]
		public extern IntSet.union (IntSet left, IntSet right);

		[CCode (cname = "context_provider_intset_add")]
		public extern void add (uint element);
		[CCode (cname = "context_provider_intset_clear")]
		public extern void clear ();
		[CCode (cname = "context_provider_intset_dump")]
		public extern weak string dump ();
		[CCode (cname = "context_provider_intset_foreach")]
		public extern void @foreach (IntFunc func, void* userdata);
		[CCode (cname = "context_provider_intset_is_equal")]
		public extern bool is_equal (IntSet right);
		[CCode (cname = "context_provider_intset_is_member")]
		public extern bool is_member (uint element);
		[CCode (cname = "context_provider_intset_is_subset_of")]
		public extern bool is_subset_of (IntSet right);
		[CCode (cname = "context_provider_intset_is_disjoint")]
		public extern bool is_disjoint (IntSet right);
		[CCode (cname = "context_provider_intset_remove")]
		public extern bool remove (uint element);
		[CCode (cname = "context_provider_intset_size")]
		public extern uint size ();
	}
	[CCode (cheader_filename = "intset.h", is_value_type="1")]
	internal extern struct IntSetIter {
		[CCode (cname = "context_provider_intset_iter_init")]
		public extern IntSetIter (IntSet? set);
		public extern weak IntSet? set;
		public extern uint element;
		[CCode (cname = "context_provider_intset_iter_next")]
		public extern bool next ();
	}
	[CCode (cheader_filename = "intset.h")]
	internal extern static delegate void IntFunc (uint i, void* userdata);
}
