lib_LTLIBRARIES = libcontextprovider.la

libcontextprovider_VALASOURCES_PRIV = \
	libcontextprovider/dbus_interface.vala \
	libcontextprovider/manager.vala \
	libcontextprovider/grouplist.vala \
	libcontextprovider/key_usage_counter.vala \
	libcontextprovider/subscriber.vala \
	libcontextprovider/value_compare.vala \
	libcontextprovider/group.vala \
	libcontextprovider/string_set.vala \
	$(NULL)

libcontextprovider_VALASOURCES_PUB = \
	libcontextprovider/context_provider.vala \
	$(NULL)

libcontextprovider_VALASOURCES = \
	$(libcontextprovider_VALASOURCES_PRIV) \
	$(libcontextprovider_VALASOURCES_PUB) \
	$(NULL)

libcontextprovider_VAPISOURCES = \
	libcontextprovider/intset.vapi \
	$(NULL)

libcontextprovider_GENERATEDSOURCES_PRIV = \
	$(libcontextprovider_VALASOURCES_PRIV:.vala=.c) \
	$(libcontextprovider_VALASOURCES_PRIV:.vala=.h) \
	$(libcontextprovider_VALASOURCES_PUB:.vala=.c) \
	$(NULL)

libcontextprovider_GENERATEDSOURCES_PUB = \
	$(libcontextprovider_VALASOURCES_PUB:.vala=.h) \
	$(NULL)

libcontextprovider_GENERATEDSOURCES = \
	$(libcontextprovider_GENERATEDSOURCES_PUB) \
	$(libcontextprovider_GENERATEDSOURCES_PRIV) \
	$(NULL)

libcontextprovider_la_SOURCES = \
	$(libcontextprovider_GENERATEDSOURCES_PRIV) \
	libcontextprovider/intset.c \
	libcontextprovider/intset.h \
	$(NULL)

libcontextproviderdir=$(includedir)/contextprovider

libcontextprovider_HEADERS = $(libcontextprovider_GENERATEDSOURCES_PUB)

libcontextprovider/libcontextprovider.vala.stamp contextprovider.vapi: $(libcontextprovider_VALASOURCES) $(libcontextprovider_VAPISOURCES)
	$(VALAC) -C --basedir $(top_srcdir)/libcontextprovider --vapidir=$(top_srcdir)/vapi --pkg dbus-glib-1 --pkg gee-1.0 --disable-dbus-transformation --library contextprovider $^
	touch libcontextprovider/libcontextprovider.vala.stamp

libcontextprovider_la_CFLAGS =	\
				-DG_LOG_DOMAIN=\"ContextKit\" \
				$(CONTEXTD_CFLAGS) \
				$(NULL)

libcontextprovider_la_LIBADD = \
			  $(CONTEXTD_LIBS) \
			  $(NULL)

EXTRA_DIST += \
	$(libcontextprovider_GENERATEDSOURCES) \
	$(libcontextprovider_VALASOURCES) \
	$(libcontextprovider_VAPISOURCES) \
	libcontextprovider/libcontextprovider.vala.stamp \
	contextprovider.vapi \
	$(NULL)

DISTCLEANFILES += \
	libcontextprovider/*.gcno \
	libcontextprovider/*.gcda \
	$(NULL)

MAINTAINERCLEANFILES += \
	$(libcontextprovider_GENERATEDSOURCES) \
	libcontextprovider/libcontextprovider.vala.stamp \
	$(NULL)

BUILT_SOURCES += \
	libcontextprovider/libcontextprovider.vala.stamp \
	$(NULL)

